// SMHI observation codes (Current weather) — mapping code -> English description
//Rådande väder (momentanvärde, 1 gång/tim resp 8 gånger/dygn) pamarameter id 13 . Kod returneras.

// Current weather pamameter id 13. The codes are defined by SMHI and used internationally.

const SMHI_CODES_EN = {
  0: "Cloud development could not be observed or was not observed",
  1: "Clouds have completely dissipated or decreased in extent, thickness, or density",
  2: "Sky largely unchanged",
  3: "Clouds have formed or increased in extent, thickness, or density",
  4: "Visibility reduced by smoke from fires or industrial smoke",
  5: "Dry haze (solar haze)",
  6: "Dust suspended in the air, not being stirred up by the wind at observation time",
  7: "Dust or sand being raised by the wind but no distinct dust whirl or sandstorm in sight",
  8: "Distinct dust or sand whirl at observation time or within the last hour (i.e., sandstorm)",
  9: "Sandstorm within the last hour or in sight at observation time",
  10: "Moist haze with visibility 1–10 km",
  11: "Low fog banks at the station; layer thickness not exceeding 2 m on land or 10 m at sea",
  12: "More or less continuous shallow fog at the station; layer thickness not exceeding 2 m on land or 10 m at sea",
  13: "Sheet lightning (heat lightning)",
  14: "Precipitation in sight aloft that does not reach the ground or sea surface (virga)",
  15: "Precipitation reaching the ground or sea surface in sight at a distance greater than 5 km from the station",
  16: "Precipitation reaching the ground or sea surface in sight at a distance less than 5 km but not at the station",
  17: "Thunder observed at observation time but no precipitation at the station",
  18: "Distinct strong wind gusts at the station or in sight at observation time or within the last hour",
  19: "Dust whirl or tornado at the station or in sight at observation time or within the last hour",
  20: "Drizzle or graupel within the last hour but not at observation time",
  21: "Rain within the last hour but not at observation time",
  22: "Snowfall within the last hour but not at observation time",
  23: "Sleet or ice pellets within the last hour but not at observation time",
  24: "Freezing rain or freezing drizzle within the last hour but not at observation time",
  25: "Rain shower within the last hour but not at observation time",
  26: "Snow showers or sleet showers within the last hour but not at observation time",
  27: "Hail showers with or without rain within the last hour but not at observation time",
  28: "Fog within the last hour but not at observation time",
  29: "Thunder (with or without precipitation) within the last hour but not at observation time",
  30: "Light or moderate sandstorm has weakened in intensity within the last hour",
  31: "Light or moderate sandstorm unchanged within the last hour",
  32: "Light or moderate sandstorm has started or intensified within the last hour",
  33: "Severe sandstorm has weakened within the last hour",
  34: "Severe sandstorm unchanged within the last hour",
  35: "Severe sandstorm has started or intensified within the last hour",
  36: "Low, light or moderate drifting snow",
  37: "Low but dense drifting snow",
  38: "High, light or moderate drifting snow",
  39: "High and dense drifting snow",
  40: "Fog in sight at observation time, reaching above eye level (but not fog at the station within the last hour)",
  41: "Fog banks at the station (visibility < 10)",
  42: "Fog with glimpses of sky has become thinner within the last hour",
  43: "Fog without glimpses of sky has become thinner within the last hour",
  44: "Fog with glimpses of sky unchanged within the last hour",
  45: "Fog without glimpses of sky unchanged within the last hour",
  46: "Fog with glimpses of sky has started or thickened within the last hour",
  47: "Fog without glimpses of sky has started or thickened within the last hour",
  48: "Supercooled fog with glimpses of sky",
  49: "Supercooled fog without glimpses of sky",
  50: "Light drizzle, intermittent",
  51: "Light drizzle, continuous",
  52: "Moderate drizzle, intermittent",
  53: "Moderate drizzle, continuous",
  54: "Dense drizzle, intermittent",
  55: "Dense drizzle, continuous",
  56: "Light freezing drizzle",
  57: "Moderate or dense freezing drizzle",
  58: "Light drizzle together with rain",
  59: "Moderate or dense drizzle together with rain",
  60: "Light rain, intermittent",
  61: "Light rain, continuous",
  62: "Moderate rain, intermittent",
  63: "Moderate rain, continuous",
  64: "Heavy rain, intermittent",
  65: "Heavy rain, continuous",
  66: "Light freezing rain",
  67: "Moderate or heavy freezing rain",
  68: "Light rain or drizzle mixed with snow",
  69: "Moderate or heavy rain or drizzle mixed with snow",
  70: "Light snowfall, intermittent",
  71: "Light snowfall, continuous",
  72: "Moderate snowfall, intermittent",
  73: "Moderate snowfall, continuous",
  74: "Dense snowfall, intermittent",
  75: "Dense snowfall, continuous",
  76: "Ice needles (with or without fog)",
  77: "Graupel (small hail) (with or without fog)",
  78: "Occasional snowflakes (with or without fog)",
  79: "Ice pellets",
  80: "Light rain showers",
  81: "Moderate or heavy rain showers",
  82: "Very heavy rain showers (cloudburst)",
  83: "Light sleet showers",
  84: "Moderate or heavy sleet showers",
  85: "Light snow showers",
  86: "Moderate or heavy snow showers",
  87: "Light showers of small hail or snow pellets with or without rain or sleet",
  88: "Moderate or heavy showers of small hail or snow pellets with or without rain or sleet",
  89: "Light showers of ice hail with or without rain or sleet, without thunder",
  90: "Moderate or heavy showers of ice hail with or without rain or sleet, without thunder",
  91: "Light rain at observation time; thunderstorm within the last hour but not at observation time",
  92: "Moderate or heavy rain at observation time; thunderstorm within the last hour but not at observation time",
  93: "Light snow, sleet or hail at observation time; thunderstorm within the last hour but not at observation time",
  94: "Moderate or heavy snow, sleet or hail at observation time; thunderstorm within the last hour but not at observation time",
  95: "Weak or moderate thunderstorm at observation time without hail but with rain or snow",
  96: "Weak or moderate thunderstorm at observation time with hail",
  97: "Severe thunderstorm at observation time without hail but with rain or snow",
  98: "Severe thunderstorm at observation time with sandstorm",
  99: "Severe thunderstorm at observation time with hail",
  100: "No significant weather observed",
  101: "Clouds have completely dissipated or decreased in extent, thickness, or density during the last hour",
  102: "Sky largely unchanged during the last hour",
  103: "Clouds have formed or increased in extent, thickness, or density during the last hour",
  104: "Haze or smoke or dust spread in the air, visibility greater or equal to 1 km",
  105: "Haze or smoke or dust spread in the air, visibility less than 1 km",
  110: "Moist haze with visibility 1–10 km",
  111: "Ice needles",
  112: "Distant lightning",
  118: "Distinct strong wind gusts",
  120: "Fog",
  121: "Precipitation",
  122: "Drizzle or graupel",
  123: "Rain",
  124: "Snowfall",
  125: "Freezing drizzle or rain",
  126: "Thunderstorm (with or without precipitation)",
  127: "Blowing snow or sandstorm",
  128: "Blowing snow or sandstorm, visibility >= 1 km",
  129: "Blowing snow or sandstorm, visibility < 1 km",
  130: "Fog",
  131: "Fog banks at the station",
  132: "Fog has become thinner during the last hour",
  133: "Fog unchanged during the last hour",
  134: "Fog has started or thickened during the last hour",
  135: "Supercooled fog",
  140: "Precipitation",
  141: "Light or moderate precipitation",
  142: "Heavy precipitation",
  143: "Liquid precipitation, light or moderate",
  144: "Liquid precipitation, heavy",
  145: "Frozen precipitation, light or moderate",
  146: "Frozen precipitation, heavy",
  147: "Light or moderate freezing precipitation",
  148: "Heavy freezing precipitation",
  150: "Drizzle",
  151: "Light drizzle",
  152: "Moderate drizzle",
  153: "Dense drizzle",
  154: "Light freezing drizzle",
  155: "Moderate freezing drizzle",
  156: "Dense drizzle",
  157: "Light drizzle together with rain",
  158: "Moderate or dense drizzle together with rain",
  160: "Rain",
  161: "Light rain",
  162: "Moderate rain",
  163: "Heavy rain",
  164: "Light freezing rain",
  165: "Moderate freezing rain",
  166: "Severe freezing rain",
  167: "Light rain or drizzle together with snow",
  168: "Moderate or heavy rain or drizzle together with snow",
  170: "Snowfall",
  171: "Light snowfall",
  172: "Moderate snowfall",
  173: "Dense snowfall",
  174: "Light small hail",
  175: "Moderate small hail",
  176: "Severe small hail",
  177: "Graupel",
  178: "Ice needles",
  180: "Rain showers",
  181: "Light rain showers",
  182: "Moderate rain showers",
  183: "Heavy rain showers",
  184: "Very heavy rain showers (cloudburst)",
  185: "Light snow squalls",
  186: "Moderate snow squalls",
  187: "Heavy snow squalls",
  189: "Hail",
  190: "Thunderstorm",
  191: "Weak or moderate thunderstorm without precipitation",
  192: "Weak or moderate thunderstorm with rain showers or snow squalls",
  193: "Weak or moderate thunderstorm with hail",
  194: "Severe thunderstorm without precipitation",
  195: "Severe thunderstorm with rain showers or snow squalls",
  196: "Severe thunderstorm with hail",
  199: "Tornado or waterspout",
  204: "Volcanic ash dispersed high in the air",
  206: "Thick dust haze, visibility less than 1 km",
  207: "Sea spray at the station due to strong wind",
  208: "Blowing dust (or sand)",
  209: "Strong dust or sandstorm at a distance (haboob)",
  210: "Snow haze",
  211: "Snowstorm or severe drifting snow causing extremely poor visibility",
  213: "Lightning between clouds and ground (cloud-to-ground)",
  217: "Thunder without rain shower",
  219: "Tornado or destructive tornado at the station or in sight within the last hour",
  220: "Deposition of volcanic ash",
  221: "Deposition of dust or sand",
  222: "Dew",
  223: "Wet snow deposition",
  224: "Light or moderate hoarfrost",
  225: "Severe hoarfrost",
  226: "Rime frost",
  227: "Severe icing due to freezing precipitation",
  228: "Ice crust",
  230: "Dust or sandstorm with temperature below freezing",
  239: "Severe drifting snow and/or heavy snowfall",
  241: "Fog at sea",
  242: "Valley fog",
  243: "Sea smoke in the Arctic or near Antarctica",
  244: "Advection fog (over water)",
  245: "Advection fog (over land)",
  246: "Fog over ice or snow",
  247: "Dense fog, visibility 60–90 m",
  248: "Dense fog, visibility 30–60 m",
  249: "Dense fog, visibility less than 30 m",
  250: "Drizzle, intensity less than 0.10 mm/h",
  251: "Drizzle, intensity 0.10–0.19 mm/h",
  252: "Drizzle, intensity 0.20–0.39 mm/h",
  253: "Drizzle, intensity 0.40–0.79 mm/h",
  254: "Drizzle, intensity 0.80–1.59 mm/h",
  255: "Drizzle, intensity 1.60–3.19 mm/h",
  256: "Drizzle, intensity 3.20–6.39 mm/h",
  257: "Drizzle, intensity greater than 6.40 mm/h",
  259: "Drizzle and snowfall",
  260: "Rain, intensity less than 1.0 mm/h",
  261: "Rain, intensity 1.0–1.9 mm/h",
  262: "Rain, intensity 2.0–3.9 mm/h",
  263: "Rain, intensity 4.0–7.9 mm/h",
  264: "Rain, intensity 8.0–15.9 mm/h",
  265: "Rain, intensity 16.0–31.9 mm/h",
  266: "Rain, intensity 32.0–63.9 mm/h",
  267: "Rain, intensity greater than 64.0 mm/h",
  270: "Snow, intensity less than 1.0 cm/h",
  271: "Snow, intensity 1.0–1.9 cm/h",
  272: "Snow, intensity 2.0–3.9 cm/h",
  273: "Snow, intensity 4.0–7.9 cm/h",
  274: "Snow, intensity 8.0–15.9 cm/h",
  275: "Snow, intensity 16.0–31.9 cm/h",
  276: "Snow, intensity 32.0–63.9 cm/h",
  277: "Snow, intensity greater than 64.0 cm/h",
  278: "Snowfall or ice needles from a clear sky",
  279: "Freezing wet snow",
  280: "Rain",
  281: "Freezing rain",
  282: "Snow mixed with rain",
  283: "Snowfall",
  284: "Small hail or snow pellets",
  285: "Small hail or snow pellets together with rain",
  286: "Small hail or snow pellets together with sleet",
  287: "Small hail or snow pellets together with snow",
  288: "Hail",
  289: "Hail together with rain",
  290: "Hail together with sleet",
  291: "Hail together with snow",
  292: "Showers or thunder at sea",
  293: "Showers or thunder over mountains",
  508: "No significant phenomena to report; current and past weather omitted",
  509: "No observation, data unavailable; current and past weather omitted",
  510: "Current and past weather missing though expected",
  511: "Missing value",
};

export default SMHI_CODES_EN;
